use super::{FIELDS, Session, error};
use crate::{config, error::Result};
use std::{
    io::{BufRead, Write},
    path::{Path, PathBuf},
};

pub enum Finish {
    Paused,
    Saved,
    Exported(PathBuf),
}

/// Input values are never echoed by BXDL. Each accepted answer is committed
/// before the next prompt; EOF and :cancel preserve the last checkpoint.
pub fn interact(
    session: &mut Session,
    input: &mut dyn BufRead,
    out: &mut dyn Write,
    output: Option<&Path>,
) -> Result<Finish> {
    say(
        out,
        "BXDL 설정 도우미 — macOS 우선 개발 버전\n설정 초안을 준비합니다. 설치·키 생성·DB 초기화·노드 시작은 수행하지 않습니다.\n값마다 저장합니다. :back 이전 항목, :cancel 저장 후 나가기, :help 도움말\n상대 경로는 처음 시작한 작업 디렉터리 기준이며 재개해도 유지됩니다.\n비밀번호 원문을 입력하지 마세요. 준비한 키·비밀번호 파일의 경로만 사용합니다.\n",
    )?;
    let mut index = session.next_index();
    loop {
        while let Some(field) = FIELDS.get(index) {
            let default = session.default_for(index);
            say(
                out,
                &format!(
                    "\n[{}/{}] {}\n{}\n",
                    index + 1,
                    FIELDS.len(),
                    field.label,
                    field.hint
                ),
            )?;
            if session.has_answer(field.name) {
                say(out, "Enter: 저장값 유지 > ")?;
            } else if let Some(default) = &default {
                // Defaults are generated by the product, never secret inputs.
                say(out, &format!("Enter: 기본값 {} > ", safe_default(default)))?;
            } else {
                say(out, "> ")?;
            }
            let Some(answer) = line(input)? else {
                return Ok(Finish::Paused);
            };
            match answer.as_str() {
                ":cancel" => return Ok(Finish::Paused),
                ":back" => {
                    index = index.saturating_sub(1);
                    continue;
                }
                ":help" => {
                    say(
                        out,
                        "Enter는 저장값/기본값을 사용합니다. :back으로 수정하거나 :cancel로 나간 뒤 --resume으로 이어가세요.\n",
                    )?;
                    continue;
                }
                "" if session.has_answer(field.name) => {
                    index += 1;
                    continue;
                }
                "" if default.is_none() => {
                    say(
                        out,
                        "이 항목은 필수입니다. 값을 입력하거나 :cancel로 나가세요.\n",
                    )?;
                    continue;
                }
                _ => {}
            }
            let value = if answer.is_empty() {
                default.as_deref().unwrap_or("")
            } else {
                &answer
            };
            match session.set(field.name, value) {
                Ok(()) => index += 1,
                Err(failure) if is_input_error(&failure.code) => {
                    say(
                        out,
                        &format!("{} [{}]\n", correction(&failure.code), failure.code),
                    )?;
                }
                Err(failure) => return Err(failure),
            }
        }
        let report = session.preflight()?;
        show_checks(out, &report)?;
        say(
            out,
            "\n설정 입력이 완료되었습니다. 엔진 검사는 미실행이며 노드를 시작할 수 있다는 뜻은 아닙니다.\n  save: 초안만 저장하고 종료\n  export: 설정 JSON 저장\n  edit: 입력 항목 수정\n  check: 로컬 검사 다시 실행\n  :cancel: 초안을 보존하고 나가기\n선택 [save] > ",
        )?;
        let Some(answer) = line(input)? else {
            return Ok(Finish::Paused);
        };
        match answer.as_str() {
            "" | "save" => return Ok(Finish::Saved),
            ":cancel" => return Ok(Finish::Paused),
            "check" => continue,
            "edit" | ":back" => {
                for (number, field) in FIELDS.iter().enumerate() {
                    say(out, &format!("{:2}. {}\n", number + 1, field.label))?;
                }
                say(out, "수정할 항목 번호 (:cancel 나가기) > ")?;
                let Some(answer) = line(input)? else {
                    return Ok(Finish::Paused);
                };
                if answer == ":cancel" {
                    return Ok(Finish::Paused);
                }
                if let Some(number) = answer
                    .parse::<usize>()
                    .ok()
                    .filter(|n| (1..=FIELDS.len()).contains(n))
                {
                    index = number - 1;
                } else {
                    say(out, "목록의 번호를 입력하세요.\n")?;
                }
            }
            "export" => {
                let destination = match output {
                    Some(path) => path.to_path_buf(),
                    None => {
                        say(
                            out,
                            "출력 파일 경로 (Enter: 작업 폴더의 instance.json, :cancel 나가기) > ",
                        )?;
                        let Some(answer) = line(input)? else {
                            return Ok(Finish::Paused);
                        };
                        if answer == ":cancel" {
                            return Ok(Finish::Paused);
                        }
                        if answer.is_empty() {
                            session.path().join("instance.json")
                        } else {
                            PathBuf::from(answer)
                        }
                    }
                };
                // Confirm the concrete target, after checking it is safe text.
                let destination = super::absolute(&destination)?;
                say(
                    out,
                    &format!(
                        "새 설정 파일: {}\n기존 파일은 덮어쓰지 않습니다. 설치·초기화·시작은 수행하지 않습니다.\n이 파일을 저장할까요? [y/N] > ",
                        destination.display()
                    ),
                )?;
                let Some(answer) = line(input)? else {
                    return Ok(Finish::Paused);
                };
                if answer == ":cancel" {
                    return Ok(Finish::Paused);
                }
                if answer != "y" && answer != "yes" {
                    say(out, "파일 저장을 취소했습니다. 초안은 보존됩니다.\n")?;
                    continue;
                }
                match session.export(&destination) {
                    Ok(path) => return Ok(Finish::Exported(path)),
                    Err(failure) => say(
                        out,
                        &format!(
                            "설정 파일을 저장하지 못했습니다. 초안은 보존됩니다. {} [{}]\n다른 경로를 사용하려면 --resume으로 다시 실행하세요.\n",
                            failure.message, failure.code
                        ),
                    )?,
                }
            }
            _ => say(out, "save, export, edit, check 중 하나를 선택하세요.\n")?,
        }
    }
}

fn line(input: &mut dyn BufRead) -> Result<Option<String>> {
    let mut raw = Vec::new();
    let count = std::io::Read::take(input, 4098)
        .read_until(b'\n', &mut raw)
        .map_err(|_| {
            error(
                "SETUP_INPUT_FAILED",
                "입력을 읽지 못했습니다. --resume으로 다시 시작하세요.",
            )
        })?;
    if count == 0 {
        return Ok(None);
    }
    if raw.last() == Some(&b'\n') {
        raw.pop();
    }
    if raw.last() == Some(&b'\r') {
        raw.pop();
    }
    if raw.len() > 4096 {
        return Err(error(
            "SETUP_INPUT_TOO_LARGE",
            "입력이 너무 깁니다. 마지막 저장 초안은 유지됩니다.",
        ));
    }
    let value = String::from_utf8(raw)
        .map_err(|_| error("SETUP_INPUT_INVALID", "입력은 UTF-8 텍스트여야 합니다."))?;
    if value.chars().any(char::is_control) {
        return Err(error(
            "SETUP_INPUT_INVALID",
            "입력에 제어문자를 사용할 수 없습니다.",
        ));
    }
    Ok(Some(value))
}

fn say(out: &mut dyn Write, message: &str) -> Result<()> {
    out.write_all(message.as_bytes())
        .and_then(|_| out.flush())
        .map_err(|_| {
            error(
                "SETUP_OUTPUT_FAILED",
                "안내를 출력하지 못했습니다. --resume으로 다시 시작하세요.",
            )
        })
}

fn safe_default(value: &str) -> String {
    value.chars().filter(|c| !c.is_control()).collect()
}

fn show_checks(out: &mut dyn Write, report: &config::Report) -> Result<()> {
    say(out, "\n로컬 사전 검사 (파일 종류·권한만 확인)\n")?;
    for check in &report.checks {
        if check.status == "FAIL" {
            say(
                out,
                &format!(
                    "  • {}: {}\n",
                    check_label(&check.name),
                    check_correction(&check.reason_code)
                ),
            )?;
        }
    }
    if report.outcome == "FAIL" {
        say(
            out,
            "누락된 자료를 준비하거나 edit으로 경로를 수정한 뒤 check로 다시 검사하세요. 실패 상태에서도 설정 초안은 저장할 수 있습니다.\n",
        )?;
    } else {
        say(
            out,
            "로컬 항목 검사가 끝났습니다. 엔진·키 내용·DB·포트 가용성·서비스 검사는 남아 있습니다.\n",
        )?;
    }
    Ok(())
}

fn check_label(name: &str) -> &str {
    match name {
        "configMetadata" => "설정 파일",
        "chainDescriptionMetadata" => "공통 체인 자료",
        "validatorKeystoreMetadata" => "Validator keystore",
        "validatorPasswordMetadata" => "Validator 비밀번호 파일",
        "tlsKeyStoreMetadata" => "TLS keystore",
        "tlsKeyPasswordMetadata" => "TLS keystore 비밀번호 파일",
        "tlsTrustStoreMetadata" => "TLS truststore",
        "tlsTrustPasswordMetadata" => "TLS truststore 비밀번호 파일",
        "dataDirectoryMetadata" => "데이터 저장 위치",
        _ => "입력 자료",
    }
}

fn check_correction(code: &str) -> &str {
    match code {
        "REFERENCE_MISSING" => "파일이 없습니다. 준비한 자료의 경로를 확인하세요.",
        "REFERENCE_SYMLINK" => "링크가 아닌 실제 파일 경로를 지정하세요.",
        "REFERENCE_NOT_REGULAR" => "디렉터리 대신 일반 파일을 지정하세요.",
        "REFERENCE_PERMISSIONS_UNSAFE" => {
            "파일 권한을 확인하세요. 키·비밀번호 파일은 본인만 읽고 쓸 수 있게 두는 것이 좋습니다."
        }
        "SECRET_DIRECTORY_PERMISSIONS_UNSAFE" => {
            "키·비밀번호 파일의 상위 폴더 접근 권한을 제한하세요."
        }
        "DATA_PERMISSIONS_UNSAFE" => "데이터 폴더의 접근 권한을 제한하세요.",
        "DATA_NOT_DIRECTORY" => "데이터 위치는 디렉터리여야 합니다.",
        _ => "파일 종류와 상위 경로의 접근 권한을 확인하세요.",
    }
}

fn is_input_error(code: &str) -> bool {
    matches!(
        code,
        "SETUP_INPUT_INVALID"
            | "SETUP_PATH_INVALID"
            | "SETUP_PATH_UNAVAILABLE"
            | "INSTANCE_ID_INVALID"
            | "NODE_ID_INVALID"
            | "HTTP_ADDRESS_INVALID"
            | "P2P_ADDRESS_INVALID"
            | "PORTS_INVALID"
            | "REFERENCE_PATH_INVALID"
            | "REFERENCE_PATH_CONFLICT"
            | "SETUP_PATH_CONFLICT"
            | "CONFIG_SCHEMA_INVALID"
    )
}

fn correction(code: &str) -> &'static str {
    match code {
        "INSTANCE_ID_INVALID" => {
            "이름은 소문자로 시작하고 소문자·숫자·하이픈으로 1~32자만 사용하세요."
        }
        "NODE_ID_INVALID" => {
            "공개 노드 ID 형식을 확인하세요. 영숫자로 시작하는 1~128자의 영숫자·점·밑줄·콜론·하이픈을 사용합니다."
        }
        "HTTP_ADDRESS_INVALID" => "로컬 콘솔 IP는 127.0.0.1 또는 ::1이어야 합니다.",
        "P2P_ADDRESS_INVALID" => "P2P에는 wildcard·multicast가 아닌 명시적인 IP 주소를 입력하세요.",
        "PORTS_INVALID" => "포트는 1~65535의 정수이며 HTTP와 P2P가 서로 달라야 합니다.",
        "SETUP_PATH_CONFLICT" => "데이터·체인·키 자료는 setup 작업 폴더와 분리하세요.",
        "REFERENCE_PATH_CONFLICT" => "데이터 디렉터리와 입력 파일 경로를 서로 다르게 지정하세요.",
        "REFERENCE_PATH_INVALID" | "SETUP_PATH_INVALID" | "SETUP_PATH_UNAVAILABLE" => {
            "실제 파일 경로를 입력하세요. ~ 축약·제어문자·설정 자기 참조는 사용할 수 없습니다."
        }
        _ => "입력 형식을 확인한 뒤 다시 입력하세요.",
    }
}
